@startuml cloud


cloud provider {

node server {

node docker {


node server [
<b>nginx
====
PORT 80 & 443
]

node phpserver [
<b>php-fpm
====
PORT 9000 OR unix socket
====
<b>run laravel artisan
]

database pgsql [
<b>postgres
====
PORT 5432
]

node laravel [
    <b>Laravel
]


component npm [
<b>run npm
]

component composer [
<b>run composer 2
]

}
}
}

node client [
<b>navigateur
]


client <- server : res
client -> server : req
server -> laravel : req
server <- laravel : res
laravel -> phpserver : req
laravel <- phpserver : res
phpserver -> pgsql : req
phpserver <- pgsql : res
phpserver -- composer
composer -- laravel : maintain
laravel -- npm

@enduml