@startuml docker


participant NAVIGATEUR as nav


box serverhttp #f0f
entity      APACHE      as apache #blue
entity      PHP         as php #blue
end box

box LARAVEL #LightSeaGreen
participant router as ENTRYPOINT
participant views as V
participant controller as C
participant model as M
end box


database    POSTGRESQL  as pgsql #yellow


nav -> apache : To apache REQUEST
apache -> php : To php REQUEST
php -> pgsql  : To pgsql REQUEST


ENTRYPOINT -> C : transmettre une request
C -> M          : transmettre une request
C <- M          : transmettre une response

C -> V          : transmettre une des données
V -> php        : compile le template une des données
php -> apache   : envoie le html
apache -> nav   :  Envoie la réponse finale

php <- pgsql  : To php RESPONSE
apache <- php : To apache RESPONSE
nav <- apache : To nav RESPONSE


@enduml